---

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: commerce.dev
vagrant_machine_name: commerce
vagrant_ip: 0.0.0.0
